### ISSUE TITLE
Parser Error in Spark environment

### ISSUE THREAD

**Issue by karanjeets** [USCDataScience/nutch-analytics#4]
The parsing is working fine in the local environment but producing errors when running in Spark environment

**Cause:** https://github.com/USCDataScience/nutch-analytics/blob/master/src/main/scala/gov/nasa/jpl/analytics/tika/TikaParser.java#L68

**Error:**
```
17/01/09 06:20:08 WARN scheduler.TaskSetManager: Lost task 30.0 in stage 3.0 (TID 658, c251-102.wrangler.tacc.utexas.edu): java.lang.RuntimeException: java.lang.RuntimeException: x 
point org.apache.nutch.parse.Parser not found.
	at gov.nasa.jpl.analytics.tika.TikaParser.<init>(TikaParser.java:47)
	at gov.nasa.jpl.analytics.tika.TikaParser.getInstance(TikaParser.java:55)
	at gov.nasa.jpl.analytics.nutch.SegmentReader$.toSparkler(SegmentReader.scala:264)
	at gov.nasa.jpl.analytics.tools.dump.CrawlDumper$$anonfun$4.apply(CrawlDumper.scala:154)
	at gov.nasa.jpl.analytics.tools.dump.CrawlDumper$$anonfun$4.apply(CrawlDumper.scala:154)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply$mcV$sp(PairRDDFunctions.scala:1198)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply(PairRDDFunctions.scala:1197)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13$$anonfun$apply$6.apply(PairRDDFunctions.scala:1197)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1250)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1205)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1$$anonfun$13.apply(PairRDDFunctions.scala:1185)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: x point org.apache.nutch.parse.Parser not found.
	at org.apache.nutch.parse.ParserFactory.<init>(ParserFactory.java:72)
	at org.apache.nutch.parse.ParseUtil.<init>(ParseUtil.java:56)
	at gov.nasa.jpl.analytics.tika.TikaParser.<init>(TikaParser.java:42)
	... 19 more
```

**Comment by thammegowda** [comment]
Hi @karanjeets,

With reference to `java.lang.RuntimeException: x point org.apache.nutch.parse.Parser not found.` : 

This happens when plugin directories are not-configured/misconfigured. It is saying that there is no parser plugin that can be attached to the specified extension point.

Suggestions:
- https://wiki.apache.org/nutch/RunNutchInEclipse#Plugin_directory_not_found
- If you have HDFS or shared file system, copy all plugins to a specific path and configure its absolute path to `plugin.folders` (as in the above link)

**Comment by karanjeets** [comment]
Thanks @thammegowda 
You correctly pointed out the issue but the problem was with respect to the NUTCH_HOME environment variable. To access environment variable in Spark environment, I ran spark-submit with following and it worked.

`--conf 'spark.executor.extraJavaOptions=-DNUTCH_HOME=Path_to_Nutch_Home_Directory'`
